me: 1
kvserver:
  password: 123456
  port: 8080
  maxRaftState: 30
  sessionTimeout: 3600000
  SessionIdSeparator: '-'
raft:
  port: 8081
  server-addresses: ['112.42.24.232:8084', '127.0.0.1:8083']
  randomInterval: 150
  electionTimeout: 360
  log:
    requestVoteEnabled: false
    appendEntryEnabled: false
    installSnapshotEnabled: false
    persistEnabled: false